import axios from "axios";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import Swal from "sweetalert2";
import Cookies from "js-cookie";
import { useRouter } from "next/router";
import Logo from "../assets/Icon.svg";
import React, { Fragment, useState } from "react";
import styles from "../styles/Login.module.css";

const LoginForm = () => {
  const [userFormData, setUserFormData] = useState({
    email: "",
    password: "",
  });

  const router = useRouter();

  const handleChange = (e) => {
    e.preventDefault();
    setUserFormData({
      ...userFormData,
      [e.target.name]: e.target.value,
    });
  };

  const handleLogin = async (e) => {
    e.preventDefault();

    const result = await axios
      .post(`http://localhost:5500/auth`, userFormData)
      .then((result) => {
        console.log(result.data);
        Swal.fire({
          title: result.data.message,
          icon: "success",
        });
        Cookies.set("id", result.data.data.id);
        Cookies.set("token", result.data.data.token);
        router.push("/home");
      })
      .catch((error) => {
        Swal.fire({
          title: error,
          icon: "error",
        });
      });
    console.log(result);
  };

  return (
    <Fragment>
      <Head>
        <title>Scoreboard - Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon-logo.ico" />
      </Head>
      <div className={`${styles.body}`}>
        <div className="container-fluid py-3 ">
          <div className="d-flex align-items-center justify-content-center  ">
            <div
              className={` d-none d-lg-flex ${styles.backdroplogin} ${styles.column} align-items-center justify-content-center`}
            >
              <div className="mt-4 me-3">
                <Image
                  className={styles.logo}
                  src={Logo}
                  height={30}
                  alt="Logo"
                />
              </div>
              <div className="d-flex align-items-center">
                {/* <h1 className="text-white mx-5 w-75">
                  Temukan developer berbakat & terbaik di berbagai bidang
                  keahlian
                </h1> */}
              </div>
            </div>
            <div className="container-fluid ">
              <div
                className={`${styles.column} d-flex align-items-center justify-content-center`}
              >
                <form
                  method="POST"
                  className={`d-flex flex-column ${styles.login} justify-content-center align-items-center`}
                >
                  <h1 className="text-center title-text">
                    <b>Halo</b>
                  </h1>
                  <p className="subtitle-text text-center fs-5 my-4">
                    Masuk dengan akun yang anda miliki!
                  </p>
                  <label
                    className={`align-self-start ${styles.inputLabelText} fw-bold`}
                    htmlFor="email"
                  >
                    E-mail
                  </label>
                  <input
                    type="email"
                    name="email"
                    className={`${styles.login} form-control my-2 mb-4`}
                    placeholder="email"
                    onChange={handleChange}
                  />
                  <label
                    className={`align-self-start ${styles.inputLabelText} fw-bold`}
                    htmlFor="password"
                  >
                    Password
                  </label>
                  <input
                    type="password"
                    name="password"
                    className={`${styles.login} form-control my-2 mb-4`}
                    placeholder="Password"
                    onChange={handleChange}
                  />
                  <div className="align-self-end fw-bold text-secondary mb-4">
                    <label className=" mt-4">Lupa kata sandi?</label>
                  </div>

                  <button
                    type="submit"
                    className={`btn btn-warning ${styles.submit} text-white fs-5 w-100`}
                    onClick={(e) => handleLogin(e)}
                  >
                    Login
                  </button>

                  <br />
                  <label className="align-self-center fw-bold text-secondary">
                    Belum memiliki akun?
                    <Link href="../register/worker">
                      <span className="text-warning ms-1">Daftar disini</span>
                    </Link>
                  </label>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </Fragment>
  );
};

export default LoginForm;
